language: node_js
matrix:
  include:
    - node_js: "6"
    - node_js: "7"
    - node_js: "7"
      env: RUN_RECIPES=1
  allow_failures:
    - node_js: "7"
      env: RUN_RECIPES=1
dist: trusty
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - npm install -g yarn@v0.22.0
install:
  - yarn install
before_script:
  - export DISPLAY=:99.0
  - export LIGHTHOUSE_CHROMIUM_PATH="$(pwd)/chrome-linux/chrome"
  - sh -e /etc/init.d/xvfb start
  - curl -L https://raw.githubusercontent.com/GoogleChrome/lighthouse/master/lighthouse-core/scripts/download-chrome.sh | bash
